# Timing
DOUBLE_PRESS_TIME = 0.3
CHORD_TAP_MAX_S = 0.25
LONG_HOLD_THRESH_S = 0.5
NAV_REJECT_FLASH_S = 0.15

# Fader smoothing (physical ADC)
SLOW_SMOOTHING_FACTOR = 0.2
FAST_SMOOTHING_FACTOR = 0.85
MOVEMENT_THRESHOLD = 1000
MIDDLE_RANGE_START = 30000
MIDDLE_RANGE_END = 40000
MIDDLE_RANGE_SMOOTHING_FACTOR = 0.05

ADAPTIVE_BUFFER_SIZE = 5
ADAPTIVE_STABLE_THRESHOLD_CC = 3
ADAPTIVE_MOVING_THRESHOLD_CC = 1
ADAPTIVE_STABILITY_RANGE = 3
ADAPTIVE_HOLD_DURATION = 1.0
ADAPTIVE_SMOOTHING_FACTOR = 0.3
ADAPTIVE_RAW_TO_CC_DIVISOR = 512

MIN_CC_VALUE = 0
MAX_CC_VALUE = 127

# SysEx: non-commercial manufacturer ID + device sub-ID
SYSEX_MANUFACTURER_ID = 0x7D
SYSEX_DEVICE_ID = 0x01
SYSEX_PROTOCOL_VERSION = 0x01

MSG_VISIBLE_STATE = 0x10
MSG_WORKSPACE_CHANGE = 0x11
MSG_SCOPE_CHANGE = 0x12

# Fader LED modes (from Bitwig)
FADER_MODE_UNIPOLAR = 0
FADER_MODE_BIPOLAR = 1
FADER_MODE_DIM = 2

# Navigation reject edges
EDGE_NONE = 0
EDGE_LEFT = 1
EDGE_RIGHT = 2
EDGE_TOP = 3
EDGE_BOTTOM = 4

# Gesture IDs (controller -> Bitwig via CC)
GESTURE_WORKSPACE = 1
GESTURE_SCOPE_TOGGLE = 2
GESTURE_NAV_NEXT_TRACK = 3
GESTURE_NAV_PREV_TRACK = 4
GESTURE_NAV_NEXT_DEVICE = 5
GESTURE_NAV_PREV_DEVICE = 6
GESTURE_NAV_NEXT_TRACK_PAGE = 7
GESTURE_NAV_PREV_TRACK_PAGE = 8
GESTURE_NAV_NEXT_SEND = 9
GESTURE_NAV_PREV_SEND = 10
GESTURE_OVERLAY_HOLD = 11

# Workspaces
WORKSPACE_FOCUS = 0
WORKSPACE_FOUR_TRACK = 1
WORKSPACE_USER = 2

# Hardware button indices (bottom = 0, top = 3)
BUTTON_1 = 0
BUTTON_2 = 1
BUTTON_3 = 2
BUTTON_4 = 3

# Colors
COLOR_REJECT = (255, 0, 0)
COLOR_OFF = (0, 0, 0)
